name: Onésimo Batista
description: Tech, music and Languages
meta_description: "Onésimo Batista, Tech, Music, Languages"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://onesimo.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: 'https://onesimo.github.io'

author:
  name: Onésimo Batista
  thumb: /assets/images/profile.jpg
  bio: Desenvolvedor web.
  url:
    facebook: 'https://www.facebook.com/onesimobatista'
    linkedin: 'http://br.linkedin.com/in/onesimo'
    email: 'onesimobatista@gmail.com'

urls:
  about: /about

img_path: /assets/images/